export const PATTERN_SECTIONS = [
  { pattern: 4, title: 'Arcs',      subtitle: 'Concentric shapes and gradients' },
  { pattern: 0, title: 'Hills',     subtitle: 'Landscapes with soft relief and trees' },
  { pattern: 1, title: 'Waves',     subtitle: 'Smooth and fluid curves' },
  { pattern: 3, title: 'Mountains', subtitle: 'Rocky and dramatic peaks' },
  { pattern: 2, title: 'Dunes',     subtitle: 'Organic wavy textures' },
  { pattern: 5, title: 'Desert',    subtitle: 'Abstract lines and free curves' },
  { pattern: 6, title: 'Blobs',     subtitle: 'Smooth concentric organic shapes' },
  { pattern: 7, title: 'Spiral',    subtitle: 'Coiled gradients and winding paths' },
];

export const wallpapers = [
  // ── Hills (pattern 0) — seed 2718 ── Light
  { id: 'hills-fire',           name: 'Fire Hills',         pattern: 0, palette: 4,  seed: 2718, inverted: true },
  { id: 'hills-purple',         name: 'Purple Hills',         pattern: 0, palette: 5,  seed: 2718, inverted: true },
  { id: 'hills-toxic',          name: 'Toxic Hills',       pattern: 0, palette: 6,  seed: 2718, inverted: true },
  { id: 'hills-neon',           name: 'Neon Hills',         pattern: 0, palette: 8,  seed: 2718, inverted: true },
  { id: 'hills-cosmic',         name: 'Cosmic Hills',      pattern: 0, palette: 11, seed: 2718, inverted: true },
  { id: 'hills-blue',           name: 'Blue Hills',         pattern: 0, palette: 2,  seed: 2718, inverted: true },
  { id: 'hills-forest',         name: 'Forest Hills',     pattern: 0, palette: 10, seed: 2718, inverted: true },
  { id: 'hills-amber',          name: 'Amber Hills',        pattern: 0, palette: 7,  seed: 2718, inverted: true },
  { id: 'hills-solar',          name: 'Solar Hills',        pattern: 0, palette: 9,  seed: 2718, inverted: true },
  { id: 'hills-sunrise',        name: 'Sunrise Hills',    pattern: 0, palette: 3,  seed: 2718, inverted: true },
  { id: 'hills-charcoal',       name: 'Charcoal Hills',       pattern: 0, palette: 0,  seed: 2718, inverted: true },
  { id: 'hills-stone',          name: 'Stone Hills',        pattern: 0, palette: 1,  seed: 2718, inverted: true },
  { id: 'hills-ocean',          name: 'Ocean Hills',       pattern: 0, palette: 12, seed: 2718, inverted: true },
  { id: 'hills-blood',          name: 'Blood Hills',       pattern: 0, palette: 13, seed: 2718, inverted: true },
  // Dark
  { id: 'hills-fire-d',         name: 'Fire Hills Dark',         pattern: 0, palette: 4,  seed: 2718, inverted: false },
  { id: 'hills-purple-d',       name: 'Purple Hills Dark',         pattern: 0, palette: 5,  seed: 2718, inverted: false },
  { id: 'hills-toxic-d',        name: 'Toxic Hills Dark',       pattern: 0, palette: 6,  seed: 2718, inverted: false },
  { id: 'hills-neon-d',         name: 'Neon Hills Dark',         pattern: 0, palette: 8,  seed: 2718, inverted: false },
  { id: 'hills-cosmic-d',       name: 'Cosmic Hills Dark',      pattern: 0, palette: 11, seed: 2718, inverted: false },
  { id: 'hills-blue-d',         name: 'Blue Hills Dark',         pattern: 0, palette: 2,  seed: 2718, inverted: false },
  { id: 'hills-forest-d',       name: 'Forest Hills Dark',     pattern: 0, palette: 10, seed: 2718, inverted: false },
  { id: 'hills-amber-d',        name: 'Amber Hills Dark',        pattern: 0, palette: 7,  seed: 2718, inverted: false },
  { id: 'hills-solar-d',        name: 'Solar Hills Dark',        pattern: 0, palette: 9,  seed: 2718, inverted: false },
  { id: 'hills-sunrise-d',      name: 'Sunrise Hills Dark',    pattern: 0, palette: 3,  seed: 2718, inverted: false },
  { id: 'hills-charcoal-d',     name: 'Charcoal Hills Dark',       pattern: 0, palette: 0,  seed: 2718, inverted: false },
  { id: 'hills-stone-d',        name: 'Stone Hills Dark',        pattern: 0, palette: 1,  seed: 2718, inverted: false },
  { id: 'hills-ocean-d',        name: 'Ocean Hills Dark',       pattern: 0, palette: 12, seed: 2718, inverted: false },
  { id: 'hills-blood-d',        name: 'Blood Hills Dark',       pattern: 0, palette: 13, seed: 2718, inverted: false },

  // ── Waves (pattern 1) — seed 3141 ── Light
  { id: 'wave-fire',            name: 'Fire Wave',            pattern: 1, palette: 4,  seed: 3141, inverted: true },
  { id: 'wave-purple',          name: 'Purple Wave',            pattern: 1, palette: 5,  seed: 3141, inverted: true },
  { id: 'wave-toxic',           name: 'Toxic Wave',          pattern: 1, palette: 6,  seed: 3141, inverted: true,  featured: true},
  { id: 'wave-neon',            name: 'Neon Wave',            pattern: 1, palette: 8,  seed: 3141, inverted: true },
  { id: 'wave-cosmic',          name: 'Cosmic Wave',         pattern: 1, palette: 11, seed: 3141, inverted: true },
  { id: 'wave-blue',            name: 'Blue Wave',            pattern: 1, palette: 2,  seed: 3141, inverted: true },
  { id: 'wave-forest',          name: 'Forest Wave',        pattern: 1, palette: 10, seed: 3141, inverted: true },
  { id: 'wave-amber',           name: 'Amber Wave',           pattern: 1, palette: 7,  seed: 3141, inverted: true },
  { id: 'wave-solar',           name: 'Solar Wave',           pattern: 1, palette: 9,  seed: 3141, inverted: true },
  { id: 'wave-sunrise',         name: 'Sunrise Wave',       pattern: 1, palette: 3,  seed: 3141, inverted: true },
  { id: 'wave-charcoal',        name: 'Charcoal Wave',          pattern: 1, palette: 0,  seed: 3141, inverted: true },
  { id: 'wave-stone',           name: 'Stone Wave',           pattern: 1, palette: 1,  seed: 3141, inverted: true },
  { id: 'wave-ocean',           name: 'Ocean Wave',          pattern: 1, palette: 12, seed: 3141, inverted: true },
  { id: 'wave-blood',           name: 'Blood Wave',          pattern: 1, palette: 13, seed: 3141, inverted: true },
  // Dark
  { id: 'wave-fire-d',          name: 'Fire Wave Dark',            pattern: 1, palette: 4,  seed: 3141, inverted: false },
  { id: 'wave-purple-d',        name: 'Purple Wave Dark',            pattern: 1, palette: 5,  seed: 3141, inverted: false },
  { id: 'wave-toxic-d',         name: 'Toxic Wave Dark',          pattern: 1, palette: 6,  seed: 3141, inverted: false },
  { id: 'wave-neon-d',          name: 'Neon Wave Dark',            pattern: 1, palette: 8,  seed: 3141, inverted: false },
  { id: 'wave-cosmic-d',        name: 'Cosmic Wave Dark',         pattern: 1, palette: 11, seed: 3141, inverted: false },
  { id: 'wave-blue-d',          name: 'Blue Wave Dark',            pattern: 1, palette: 2,  seed: 3141, inverted: false },
  { id: 'wave-forest-d',        name: 'Forest Wave Dark',        pattern: 1, palette: 10, seed: 3141, inverted: false },
  { id: 'wave-amber-d',         name: 'Amber Wave Dark',           pattern: 1, palette: 7,  seed: 3141, inverted: false },
  { id: 'wave-solar-d',         name: 'Solar Wave Dark',           pattern: 1, palette: 9,  seed: 3141, inverted: false },
  { id: 'wave-sunrise-d',       name: 'Sunrise Wave Dark',       pattern: 1, palette: 3,  seed: 3141, inverted: false },
  { id: 'wave-charcoal-d',      name: 'Charcoal Wave Dark',          pattern: 1, palette: 0,  seed: 3141, inverted: false },
  { id: 'wave-stone-d',         name: 'Stone Wave Dark',           pattern: 1, palette: 1,  seed: 3141, inverted: false },
  { id: 'wave-ocean-d',         name: 'Ocean Wave Dark',          pattern: 1, palette: 12, seed: 3141, inverted: false },
  { id: 'wave-blood-d',         name: 'Blood Wave Dark',          pattern: 1, palette: 13, seed: 3141, inverted: false },

  // ── Mountains (pattern 3) — seed 1618 ── Light
  { id: 'peaks-fire',           name: 'Fire Mountains',       pattern: 3, palette: 4,  seed: 1618, inverted: true },
  { id: 'peaks-purple',         name: 'Purple Mountains',       pattern: 3, palette: 5,  seed: 1618, inverted: true },
  { id: 'peaks-toxic',          name: 'Toxic Mountains',     pattern: 3, palette: 6,  seed: 1618, inverted: true },
  { id: 'peaks-neon',           name: 'Neon Mountains',       pattern: 3, palette: 8,  seed: 1618, inverted: true },
  { id: 'peaks-cosmic',         name: 'Cosmic Mountains',    pattern: 3, palette: 11, seed: 1618, inverted: true },
  { id: 'peaks-blue',           name: 'Blue Mountains',       pattern: 3, palette: 2,  seed: 1618, inverted: true },
  { id: 'peaks-forest',         name: 'Forest Mountains',   pattern: 3, palette: 10, seed: 1618, inverted: true },
  { id: 'peaks-amber',          name: 'Amber Mountains',      pattern: 3, palette: 7,  seed: 1618, inverted: true },
  { id: 'peaks-solar',          name: 'Solar Mountains',      pattern: 3, palette: 9,  seed: 1618, inverted: true },
  { id: 'peaks-sunrise',        name: 'Sunrise Mountains',  pattern: 3, palette: 3,  seed: 1618, inverted: true },
  { id: 'peaks-charcoal',       name: 'Charcoal Mountains',     pattern: 3, palette: 0,  seed: 1618, inverted: true },
  { id: 'peaks-stone',          name: 'Stone Mountains',      pattern: 3, palette: 1,  seed: 1618, inverted: true },
  { id: 'peaks-ocean',          name: 'Ocean Mountains',     pattern: 3, palette: 12, seed: 1618, inverted: true },
  { id: 'peaks-blood',          name: 'Blood Mountains',     pattern: 3, palette: 13, seed: 1618, inverted: true },
  // Dark
  { id: 'peaks-fire-d',         name: 'Fire Mountains Dark',       pattern: 3, palette: 4,  seed: 1618, inverted: false },
  { id: 'peaks-purple-d',       name: 'Purple Mountains Dark',       pattern: 3, palette: 5,  seed: 1618, inverted: false },
  { id: 'peaks-toxic-d',        name: 'Toxic Mountains Dark',     pattern: 3, palette: 6,  seed: 1618, inverted: false },
  { id: 'peaks-neon-d',         name: 'Neon Mountains Dark',       pattern: 3, palette: 8,  seed: 1618, inverted: false },
  { id: 'peaks-cosmic-d',       name: 'Cosmic Mountains Dark',    pattern: 3, palette: 11, seed: 1618, inverted: false },
  { id: 'peaks-blue-d',         name: 'Blue Mountains Dark',       pattern: 3, palette: 2,  seed: 1618, inverted: false },
  { id: 'peaks-forest-d',       name: 'Forest Mountains Dark',   pattern: 3, palette: 10, seed: 1618, inverted: false },
  { id: 'peaks-amber-d',        name: 'Amber Mountains Dark',      pattern: 3, palette: 7,  seed: 1618, inverted: false },
  { id: 'peaks-solar-d',        name: 'Solar Mountains Dark',      pattern: 3, palette: 9,  seed: 1618, inverted: false },
  { id: 'peaks-sunrise-d',      name: 'Sunrise Mountains Dark',  pattern: 3, palette: 3,  seed: 1618, inverted: false },
  { id: 'peaks-charcoal-d',     name: 'Charcoal Mountains Dark',     pattern: 3, palette: 0,  seed: 1618, inverted: false },
  { id: 'peaks-stone-d',        name: 'Stone Mountains Dark',      pattern: 3, palette: 1,  seed: 1618, inverted: false },
  { id: 'peaks-ocean-d',        name: 'Ocean Mountains Dark',     pattern: 3, palette: 12, seed: 1618, inverted: false },
  { id: 'peaks-blood-d',        name: 'Blood Mountains Dark',     pattern: 3, palette: 13, seed: 1618, inverted: false },

  // ── Arcs (pattern 4) — seed 4669 ── Light
  { id: 'arcs-fire',            name: 'Fire Arcs',           pattern: 4, palette: 4,  seed: 4669, inverted: true },
  { id: 'arcs-purple',          name: 'Purple Arcs',           pattern: 4, palette: 5,  seed: 4669, inverted: true },
  { id: 'arcs-toxic',           name: 'Toxic Arcs',         pattern: 4, palette: 6,  seed: 4669, inverted: true },
  { id: 'arcs-neon',            name: 'Neon Arcs',           pattern: 4, palette: 8,  seed: 4669, inverted: true },
  { id: 'arcs-cosmic',          name: 'Cosmic Arcs',        pattern: 4, palette: 11, seed: 4669, inverted: true },
  { id: 'arcs-blue',            name: 'Blue Arcs',           pattern: 4, palette: 2,  seed: 4669, inverted: true },
  { id: 'arcs-forest',          name: 'Forest Arcs',       pattern: 4, palette: 10, seed: 4669, inverted: true },
  { id: 'arcs-amber',           name: 'Amber Arcs',          pattern: 4, palette: 7,  seed: 4669, inverted: true },
  { id: 'arcs-solar',           name: 'Solar Arcs',          pattern: 4, palette: 9,  seed: 4669, inverted: true },
  { id: 'arcs-sunrise',         name: 'Sunrise Arcs',      pattern: 4, palette: 3,  seed: 4669, inverted: true },
  { id: 'arcs-charcoal',        name: 'Charcoal Arcs',         pattern: 4, palette: 0,  seed: 4669, inverted: true },
  { id: 'arcs-stone',           name: 'Stone Arcs',          pattern: 4, palette: 1,  seed: 4669, inverted: true },
  { id: 'arcs-ocean',           name: 'Ocean Arcs',         pattern: 4, palette: 12, seed: 4669, inverted: true },
  { id: 'arcs-blood',           name: 'Blood Arcs',         pattern: 4, palette: 13, seed: 4669, inverted: true },
  // Dark
  { id: 'arcs-fire-d',          name: 'Fire Arcs Dark',           pattern: 4, palette: 4,  seed: 4669, inverted: false },
  { id: 'arcs-purple-d',        name: 'Purple Arcs Dark',           pattern: 4, palette: 5,  seed: 4669, inverted: false },
  { id: 'arcs-toxic-d',         name: 'Toxic Arcs Dark',         pattern: 4, palette: 6,  seed: 4669, inverted: false },
  { id: 'arcs-neon-d',          name: 'Neon Arcs Dark',           pattern: 4, palette: 8,  seed: 4669, inverted: false },
  { id: 'arcs-cosmic-d',        name: 'Cosmic Arcs Dark',        pattern: 4, palette: 11, seed: 4669, inverted: false },
  { id: 'arcs-blue-d',          name: 'Blue Arcs Dark',           pattern: 4, palette: 2,  seed: 4669, inverted: false },
  { id: 'arcs-forest-d',        name: 'Forest Arcs Dark',       pattern: 4, palette: 10, seed: 4669, inverted: false },
  { id: 'arcs-amber-d',         name: 'Amber Arcs Dark',          pattern: 4, palette: 7,  seed: 4669, inverted: false },
  { id: 'arcs-solar-d',         name: 'Solar Arcs Dark',          pattern: 4, palette: 9,  seed: 4669, inverted: false },
  { id: 'arcs-sunrise-d',       name: 'Sunrise Arcs Dark',      pattern: 4, palette: 3,  seed: 4669, inverted: false },
  { id: 'arcs-charcoal-d',      name: 'Charcoal Arcs Dark',         pattern: 4, palette: 0,  seed: 4669, inverted: false },
  { id: 'arcs-stone-d',         name: 'Stone Arcs Dark',          pattern: 4, palette: 1,  seed: 4669, inverted: false },
  { id: 'arcs-ocean-d',         name: 'Ocean Arcs Dark',         pattern: 4, palette: 12, seed: 4669, inverted: false },
  { id: 'arcs-blood-d',         name: 'Blood Arcs Dark',         pattern: 4, palette: 13, seed: 4669, inverted: false },

  // ── Dunes (pattern 2) — seed 5772 ── Light
  { id: 'dunes-fire',           name: 'Fire Dunes',           pattern: 2, palette: 4,  seed: 5772, inverted: true },
  { id: 'dunes-purple',         name: 'Purple Dunes',           pattern: 2, palette: 5,  seed: 5772, inverted: true },
  { id: 'dunes-toxic',          name: 'Toxic Dunes',         pattern: 2, palette: 6,  seed: 5772, inverted: true },
  { id: 'dunes-neon',           name: 'Neon Dunes',           pattern: 2, palette: 8,  seed: 5772, inverted: true },
  { id: 'dunes-cosmic',         name: 'Cosmic Dunes',        pattern: 2, palette: 11, seed: 5772, inverted: true },
  { id: 'dunes-blue',           name: 'Blue Dunes',           pattern: 2, palette: 2,  seed: 5772, inverted: true },
  { id: 'dunes-forest',         name: 'Forest Dunes',       pattern: 2, palette: 10, seed: 5772, inverted: true },
  { id: 'dunes-amber',          name: 'Amber Dunes',          pattern: 2, palette: 7,  seed: 5772, inverted: true },
  { id: 'dunes-solar',          name: 'Solar Dunes',          pattern: 2, palette: 9,  seed: 5772, inverted: true },
  { id: 'dunes-sunrise',        name: 'Sunrise Dunes',      pattern: 2, palette: 3,  seed: 5772, inverted: true },
  { id: 'dunes-charcoal',       name: 'Charcoal Dunes',         pattern: 2, palette: 0,  seed: 5772, inverted: true },
  { id: 'dunes-stone',          name: 'Stone Dunes',          pattern: 2, palette: 1,  seed: 5772, inverted: true },
  { id: 'dunes-ocean',          name: 'Ocean Dunes',         pattern: 2, palette: 12, seed: 5772, inverted: true },
  { id: 'dunes-blood',          name: 'Blood Dunes',         pattern: 2, palette: 13, seed: 5772, inverted: true },
  // Dark
  { id: 'dunes-fire-d',         name: 'Fire Dunes Dark',           pattern: 2, palette: 4,  seed: 5772, inverted: false },
  { id: 'dunes-purple-d',       name: 'Purple Dunes Dark',           pattern: 2, palette: 5,  seed: 5772, inverted: false },
  { id: 'dunes-toxic-d',        name: 'Toxic Dunes Dark',         pattern: 2, palette: 6,  seed: 5772, inverted: false },
  { id: 'dunes-neon-d',         name: 'Neon Dunes Dark',           pattern: 2, palette: 8,  seed: 5772, inverted: false },
  { id: 'dunes-cosmic-d',       name: 'Cosmic Dunes Dark',        pattern: 2, palette: 11, seed: 5772, inverted: false },
  { id: 'dunes-blue-d',         name: 'Blue Dunes Dark',           pattern: 2, palette: 2,  seed: 5772, inverted: false },
  { id: 'dunes-forest-d',       name: 'Forest Dunes Dark',       pattern: 2, palette: 10, seed: 5772, inverted: false },
  { id: 'dunes-amber-d',         name: 'Amber Dunes Dark',          pattern: 2, palette: 7,  seed: 5772, inverted: false },
  { id: 'dunes-solar-d',         name: 'Solar Dunes Dark',          pattern: 2, palette: 9,  seed: 5772, inverted: false },
  { id: 'dunes-sunrise-d',       name: 'Sunrise Dunes Dark',      pattern: 2, palette: 3,  seed: 5772, inverted: false },
  { id: 'dunes-charcoal-d',      name: 'Charcoal Dunes Dark',         pattern: 2, palette: 0,  seed: 5772, inverted: false },
  { id: 'dunes-stone-d',         name: 'Stone Dunes Dark',          pattern: 2, palette: 1,  seed: 5772, inverted: false },
  { id: 'dunes-ocean-d',         name: 'Ocean Dunes Dark',         pattern: 2, palette: 12, seed: 5772, inverted: false },
  { id: 'dunes-blood-d',         name: 'Blood Dunes Dark',         pattern: 2, palette: 13, seed: 5772, inverted: false },

  // ── Desert (pattern 5) — seed 8811 ── Light
  { id: 'desert-fire',          name: 'Fire Desert',         pattern: 5, palette: 4,  seed: 8811, inverted: true },
  { id: 'desert-purple',        name: 'Purple Desert',         pattern: 5, palette: 5,  seed: 8811, inverted: true },
  { id: 'desert-toxic',         name: 'Toxic Desert',       pattern: 5, palette: 6,  seed: 8811, inverted: true },
  { id: 'desert-neon',          name: 'Neon Desert',         pattern: 5, palette: 8,  seed: 8811, inverted: true },
  { id: 'desert-cosmic',        name: 'Cosmic Desert',      pattern: 5, palette: 11, seed: 8811, inverted: true },
  { id: 'desert-blue',          name: 'Blue Desert',         pattern: 5, palette: 2,  seed: 8811, inverted: true },
  { id: 'desert-forest',        name: 'Forest Desert',     pattern: 5, palette: 10, seed: 8811, inverted: true },
  { id: 'desert-amber',         name: 'Amber Desert',        pattern: 5, palette: 7,  seed: 8811, inverted: true },
  { id: 'desert-solar',         name: 'Solar Desert',        pattern: 5, palette: 9,  seed: 8811, inverted: true },
  { id: 'desert-sunrise',       name: 'Sunrise Desert',    pattern: 5, palette: 3,  seed: 8811, inverted: true },
  { id: 'desert-charcoal',      name: 'Charcoal Desert',       pattern: 5, palette: 0,  seed: 8811, inverted: true },
  { id: 'desert-stone',         name: 'Stone Desert',        pattern: 5, palette: 1,  seed: 8811, inverted: true },
  { id: 'desert-ocean',         name: 'Ocean Desert',       pattern: 5, palette: 12, seed: 8811, inverted: true },
  { id: 'desert-blood',         name: 'Blood Desert',       pattern: 5, palette: 13, seed: 8811, inverted: true },
  // Dark
  { id: 'desert-fire-d',        name: 'Fire Desert Dark',         pattern: 5, palette: 4,  seed: 8811, inverted: false },
  { id: 'desert-purple-d',      name: 'Purple Desert Dark',         pattern: 5, palette: 5,  seed: 8811, inverted: false },
  { id: 'desert-toxic-d',       name: 'Toxic Desert Dark',       pattern: 5, palette: 6,  seed: 8811, inverted: false },
  { id: 'desert-neon-d',        name: 'Neon Desert Dark',         pattern: 5, palette: 8,  seed: 8811, inverted: false },
  { id: 'desert-cosmic-d',      name: 'Cosmic Desert Dark',      pattern: 5, palette: 11, seed: 8811, inverted: false },
  { id: 'desert-blue-d',        name: 'Blue Desert Dark',         pattern: 5, palette: 2,  seed: 8811, inverted: false },
  { id: 'desert-forest-d',      name: 'Forest Desert Dark',     pattern: 5, palette: 10, seed: 8811, inverted: false },
  { id: 'desert-amber-d',       name: 'Amber Desert Dark',        pattern: 5, palette: 7,  seed: 8811, inverted: false },
  { id: 'desert-solar-d',       name: 'Solar Desert Dark',        pattern: 5, palette: 9,  seed: 8811, inverted: false },
  { id: 'desert-sunrise-d',     name: 'Sunrise Desert Dark',    pattern: 5, palette: 3,  seed: 8811, inverted: false },
  { id: 'desert-charcoal-d',    name: 'Charcoal Desert Dark',       pattern: 5, palette: 0,  seed: 8811, inverted: false },
  { id: 'desert-stone-d',       name: 'Stone Desert Dark',        pattern: 5, palette: 1,  seed: 8811, inverted: false },
  { id: 'desert-ocean-d',       name: 'Ocean Desert Dark',       pattern: 5, palette: 12, seed: 8811, inverted: false },
  { id: 'desert-blood-d',       name: 'Blood Desert Dark',       pattern: 5, palette: 13, seed: 8811, inverted: false },

  // ── Blobs (pattern 6) — seed 1234 ──
  { id: 'blobs-cyberpunk',      name: 'Cyberpunk Blobs',      pattern: 6, palette: 15, seed: 1234, inverted: false },
  { id: 'blobs-sunset',         name: 'Sunset Blobs',         pattern: 6, palette: 14, seed: 5678, inverted: false },
  { id: 'blobs-lavender',       name: 'Lavender Blobs',       pattern: 6, palette: 17, seed: 9012, inverted: true },
  { id: 'blobs-emerald',        name: 'Emerald Blobs',        pattern: 6, palette: 16, seed: 3456, inverted: false },
  { id: 'blobs-retro',          name: 'Retro Blobs',          pattern: 6, palette: 18, seed: 7890, inverted: false },

  // ── Spiral (pattern 7) — seed 4321 ──
  { id: 'spiral-neon',          name: 'Neon Vortex',          pattern: 7, palette: 8,  seed: 4321, inverted: false },
  { id: 'spiral-retro',         name: 'Retro Vortex',         pattern: 7, palette: 18, seed: 8765, inverted: false },
  { id: 'spiral-emerald',       name: 'Emerald Vortex',       pattern: 7, palette: 16, seed: 2109, inverted: true },
  { id: 'spiral-sunset',        name: 'Sunset Vortex',        pattern: 7, palette: 14, seed: 6543, inverted: false },
  { id: 'spiral-cyberpunk',     name: 'Cyberpunk Vortex',     pattern: 7, palette: 15, seed: 9876, inverted: false },
];

export function getWallpaper(id) {
  return wallpapers.find(w => w.id === id);
}

export function getFeatured() {
  return wallpapers.find(w => w.featured) || wallpapers[0];
}
